//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upc_website
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        public string ChID { get; set; }
        public string BkID { get; set; }
        public int VsCnt { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
