//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upc_website
{
    using System;
    using System.Collections.Generic;
    
    public partial class SermonAudio
    {
        public int SermonAudioID { get; set; }
        public string Title { get; set; }
        public string ImageURL { get; set; }
        public string Speaker { get; set; }
        public string C1Book { get; set; }
        public Nullable<int> C1Chapter { get; set; }
        public Nullable<int> C1VerseStart { get; set; }
        public Nullable<int> C1VerseEnd { get; set; }
        public string C2Book { get; set; }
        public Nullable<int> C2Chapter { get; set; }
        public Nullable<int> C2VerseStart { get; set; }
        public Nullable<int> C2VerseEnd { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> SeriesID { get; set; }
        public Nullable<int> SeriesOrder { get; set; }
        public Nullable<System.DateTime> SermonDt { get; set; }
        public string SermonAMPM { get; set; }
        public string Notes { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Book Book1 { get; set; }
        public virtual Event Event { get; set; }
        public virtual Series Series { get; set; }
    }
}
