//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upc_website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carousel_images
    {
        public int id { get; set; }
        public string picName { get; set; }
        public string path { get; set; }
        public System.DateTime beginDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string lineOneCaption { get; set; }
        public string lineTwoCaption { get; set; }
        public string lineThreeCaption { get; set; }
        public string url { get; set; }
        public string urlLocation { get; set; }
    }
}
